
rpc_cli: rpc_cli.nim
	nim c --nimblePath:$(HOME)/.nimble/pkgs rpc_cli.nim


rpc_server_example: rpc_server_example.nim
	nim c --nimblePath:$(HOME)/.nimble/pkgs rpc_server_example.nim

clean:
	rm -Rf rpc_cli rpc_server_example

